name: "infa-workflow"
on: push
jobs:
  job_name: 
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read
    steps: 
    - name: Checkout
      uses: actions/checkout@v5.0.0
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        version: 1.13.0
    - name: Azure Login
      uses: Azure/login@v2.3.0
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    
    - name: Terraform Init
      run: terraform init
      working-directory: dev
    - name: Terraform Plan
      run: terraform plan
      working-directory: dev
    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: dev

    
    
          
